/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import Controladores.ControladorVentanaDevolucionLibro;
import Modelos.Libro;
import Modelos.PrestamoLibro;
import Modelos.Usuario;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cduar
 */
public class VentanaDevolucionLibro extends javax.swing.JFrame {
    private  ControladorVentanaDevolucionLibro controlador;
    DefaultTableModel modelo;
    private Usuario usuario;

    /**
     * Creates new form VentanaDevolucionLibro
     */
    public VentanaDevolucionLibro(  Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        this.controlador = new ControladorVentanaDevolucionLibro();
        modelo=(DefaultTableModel)tablaLibrosEnPrestamo.getModel();
        actualizarComboBox(usuario.getCedula());
        actualizarTabla(usuario.getCedula());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibrosEnPrestamo = new javax.swing.JTable();
        btVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btDevolucion = new javax.swing.JButton();
        cboPrestamo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaLibrosEnPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Prestamo", "Codido Libro", "Nombre del Libro", "Fecha Prestamo", "Fecha Vencimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaLibrosEnPrestamo);
        if (tablaLibrosEnPrestamo.getColumnModel().getColumnCount() > 0) {
            tablaLibrosEnPrestamo.getColumnModel().getColumn(0).setResizable(false);
            tablaLibrosEnPrestamo.getColumnModel().getColumn(1).setResizable(false);
            tablaLibrosEnPrestamo.getColumnModel().getColumn(2).setResizable(false);
            tablaLibrosEnPrestamo.getColumnModel().getColumn(3).setResizable(false);
            tablaLibrosEnPrestamo.getColumnModel().getColumn(4).setResizable(false);
        }

        btVolver.setText("Volver");
        btVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Libro para su Devolución"));

        btDevolucion.setText("Regresar Libro");
        btDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDevolucionActionPerformed(evt);
            }
        });

        jLabel1.setText("Id Prestamo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addComponent(cboPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btDevolucion)
                        .addGap(37, 37, 37)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btDevolucion)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVolver)
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDevolucionActionPerformed
        Object selectedItem = cboPrestamo.getSelectedItem();
        
        if(selectedItem.toString().equals("-Seleccionar-")){
            JOptionPane.showMessageDialog( null , " Debe escoger una libro para poder realizar el prestamo");

            return;
        }  
        
        try {
            LocalDate fecha_devolucion = LocalDate.now();
            int preestamo_id = Integer.parseInt(selectedItem.toString());
            controlador.devolucion(preestamo_id, fecha_devolucion.toString());
            actualizarTabla(usuario.getCedula());
            actualizarComboBox(usuario.getCedula());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btDevolucionActionPerformed

    private void btVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverActionPerformed
        VentanaUsuario u = new VentanaUsuario(usuario);
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVolverActionPerformed
    
    public void actualizarTabla(int cedula){
       
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo.getRowCount(); j++) {
                    modelo.removeRow(j);
                }
            }
        }catch(NullPointerException e){
        }
        try{
            ArrayList<PrestamoLibro> listaPrestamos = controlador.traerPrestamos(cedula);
            for (int i = 0; i < listaPrestamos.size(); i++) {
                PrestamoLibro aux = listaPrestamos.get(i);
                Libro libro = controlador.buscarLibro(aux.getCodigo_libro());
                Object[] ob = {aux.getId_prestamo() , aux.getCodigo_libro() , libro.getTitulo() , aux.getFechaPrestamo(),aux.getFechaVencimiento()};
                modelo.addRow(ob);
            }

            }catch(Exception ex){
                System.err.println(ex.toString());
            }
    }
    public void actualizarComboBox(int cedula) {
        cboPrestamo.removeAllItems();
        try {
            ArrayList<PrestamoLibro> listaPrestamos = controlador.traerPrestamos(cedula);
            cboPrestamo.addItem("-Seleccionar-");
            for (int i = 0; i < listaPrestamos.size(); i++) {
                String item = String.valueOf(listaPrestamos.get(i).getId_prestamo());
                cboPrestamo.addItem(item);
            }
            
        } catch (Exception e) {
        }
    }
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDevolucion;
    private javax.swing.JButton btVolver;
    private javax.swing.JComboBox<String> cboPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLibrosEnPrestamo;
    // End of variables declaration//GEN-END:variables
}
